# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
image: ubuntu:xenial

before_script:
  - export LC_ALL=C.UTF-8
  - apt update
  - apt install -y python3-pip

pages:
  stage: deploy
  script:
    - pip3 install . --no-deps
    - cd _docs
    - pip3 install -r requirements-docs.txt
    - make html
    - cp -r _build/html/ ../public
  artifacts:
    paths:
      - public
  only:
    - docs
  tags:
    - general
