# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
image: ubuntu:xenial

before_script:
  - export LC_ALL=C.UTF-8
  - apt update
  - apt install -y python3-pip awscli

pages:
  stage: deploy
  script:
    - mkdir -p ~/.config/pip/
    - aws s3 cp s3://creds/pip.conf ~/.config/pip/pip.conf
    - pip3 install -U -r requirements-docs.txt .
    - cd _docs
    - make html
    - cp -r _build/html/ ../public
  artifacts:
    paths:
      - public
  only:
    - docs
  tags:
    - general
