sudo: false
language: python
python:
  - 3.4
  - 3.5
  - 3.6

cache: false

install:
  - pip install -r requirements-dev.txt

script:
  - tox
  - tox -e lint

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a57f158d4365b3598713
    on_success: always
    on_failure: always
    on_start: never
