sudo: false
language: python
python:
  - 3.4
  - 3.5
  - 3.6

env:
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=lint

matrix:
  exclude:
    - python: 3.4
      env: TOXENV=py35
    - python: 3.4
      env: TOXENV=py36
    - python: 3.4
      env: TOXENV=lint
    - python: 3.5
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py36
    - python: 3.5
      env: TOXENV=lint
    - python: 3.6
      env: TOXENV=py34
    - python: 3.6
      env: TOXENV=py35

cache: false

install:
  - pip install -r requirements-dev.txt

script:
  - tox

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a57f158d4365b3598713
    on_success: always
    on_failure: always
    on_start: never
